### ISSUE TITLE
Consistent CTAs

### ISSUE THREAD

**Issue by charisfm13** [Arize-ai/ui-components#239]
We'd like to make the CTAs more consistent across platform (styling, location, copy etc)

Summarized changes here: https://docs.google.com/document/d/1vMjz3vpU0g1jvGoe34V8gUa-w1d0u_cGUPBEZPvVInM/edit

Feel free to move this to the correct board.

@m0neysha @AparnaDhinakaran @exiao

**Comment by exiao** [comment]
Moved to https://github.com/Arize-ai/arize/issues/36252
